# Site settings
email:
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Busylessman
description: less doing same thing
url: "http://busylessman.com"
twitter_username: andihaki
default_img:

# Profile settings
name: Andi Hakim
profile_img:
profile: less doing same thing
social: 
  github: "https://github.com/andihaki"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
